### ISSUE TITLE
Uncaught TypeError: React.useRef is not a function

### ISSUE THREAD

**Issue by dramagalla** [elrumordelaluz/reactour#294]
I have installed Reactour latest version and trying to use it in my application, I see below error. Currently using "react": "16.4.0" version and cannot upgrade the application to latest React versions. Please suggest how to use Reactour and resolve issue with "16.4.0" version!

![image](https://user-images.githubusercontent.com/36393100/95783801-98099e80-0ca0-11eb-97d8-4ec0d99858d3.png)

**Comment by grant-davidson** [comment]
@dramagalla - You'll need to use one of the older releases of Reactour that doesn't use React 16.8

**Comment by dramagalla** [comment]
Can you please suggest which version of Reactour I should use. Not able to understand.

I used 1.14.0 and its giving below error

![image](https://user-images.githubusercontent.com/36393100/95802792-6b6b7c00-0ccc-11eb-95be-7d866d378511.png)

**Comment by dramagalla** [comment]
@elrumordelaluz Can you please help with above issue

**Comment by grant-davidson** [comment]
Reactour 1.14.0 works fine with React 16.4.0

You'll need to reproduce the problem in a sandbox.   You could use the one below as a starting point.

https://codesandbox.io/s/reactour-demo-template-1640-1140-8ccrz

**Comment by dramagalla** [comment]
thank you for reply @grant-davidson I have tried 1.14.0 and also installed styled-components@4.4.1. It works in sandbox but not in my application and I see the below issue
![image](https://user-images.githubusercontent.com/36393100/95949898-a00d2f80-0dc1-11eb-92b8-d23fafc800db.png)

**Comment by grant-davidson** [comment]
You'll either need to change the sandbox code to be more like your application or your application code to be more like the sandbox until you can isolate the cause of the problem.  

Maybe start by making the tour in your app as simple as possible.

**Comment by grant-davidson** [comment]
Also, there are quite a few closed issues related to getBoundingClientRect that may have a workaround/solution to the problem you are having.  It would be worth checking through those.

**Comment by elrumordelaluz** [comment]
Due to inactivity I am closing this _issue_, but feel free to re-open or create a new one in any case.
